<?php

namespace App\Filament\Pages;

use Filament\Actions\Action;
use Filament\Pages\Page;

class Video extends Page
{
    protected static ?string $navigationIcon = 'heroicon-s-pencil-square';

    protected static string $view = 'filament.pages.video';

    protected static ?string $navigationLabel = 'Загрузить видео';

    /**
     * @return string
     */
    public function getHeading(): string
    {
        return 'Загрузка видео';
    }

    public function getMaxContentWidth(): ?string
    {
        return 'full'; // TODO: Change the autogenerated stub
    }
}
